server:
  port: 8080

spring:
  application:
    name: mini-erp-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/mini_erp

jwt:
  # change this in production - use an env var (JWT_SECRET) instead of hardcoding
  secret: "change-this-to-a-long-random-secret-value-min-32-chars-please"
  expiration-ms: 86400000   # 24 hours

app:
  cors:
    allowed-origins: "http://localhost:5173"
